tap "atombender/ktail"           # ktail
tap "aws/tap"                    # ec2-metadata-mock
tap "buo/cask-upgrade"           # brew cu
tap "charmbracelet/tap"          # freeze
tap "danielfoehrkn/switch"       # switch
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "mikelorant/committed"       # committed
tap "mikelorant/tap"
tap "scullionw/tap"              # dirstat-rs
tap "theurichde/go-aws-sso"      # go-aws-sso
tap "vectordotdev/brew"          # vector

brew "antidote"
brew "aria2"
brew "asdf"
brew "asdfswitcher"
brew "aws-console"
brew "aws-iam-authenticator"
brew "awscli"
brew "bat"
brew "bind"
brew "caddy"
brew "certigo"
brew "committed"
brew "coreutils"
brew "delve"
brew "direnv"
brew "dirstat-rs"
brew "docker-completion"
brew "docker-credential-helper-ecr"
brew "dockutil"
brew "dog"
brew "ec2-metadata-mock"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "git-delete-merged-branches"
brew "git-delta"
brew "git-graph"
brew "git-lfs"
brew "glow"
brew "go-aws-sso"
brew "go-task"
brew "golangci-lint"
brew "goreleaser"
brew "gum"
brew "hadolint"
brew "httpie"
brew "jq"
brew "ktail"
brew "less"
brew "lnav"
brew "lsd"
brew "markdownlint-cli"
brew "mas"
brew "miller"
brew "minikube"
brew "mods"
brew "mtr"
brew "nano"
brew "nanorc"
brew "ncdu"
brew "okta-aws-cli"
brew "prettier"
brew "procs"
brew "pv"
brew "pwgen"
brew "ripgrep"
brew "rust"
brew "sd"
brew "shellcheck"
brew "shfmt"
brew "sshuttle"
brew "switch"
brew "ttyd"
brew "vector"
brew "vhs"
brew "viddy"
brew "vivid"
brew "wget"
brew "yamlfmt"
brew "yamllint"
brew "yq"
brew "zoxide"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "1password-cli"
cask "adguard"
cask "amazon-chime"
cask "bartender"
cask "beyond-compare"
cask "big-ip-edge-client"
cask "cleanshot"
cask "crowdstrike-falcon-sensor"
cask "daisydisk"
cask "dash6"
cask "devutils"
cask "discord"
cask "droplr"
cask "evernote"
cask "firefox"
cask "font-ibm-plex"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "gitify"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "lasso"
cask "launchpadder"
cask "leapp"
cask "little-snitch"
cask "logi-options-plus"
cask "logitune"
cask "macs-fan-control"
cask "micro-snitch"
cask "monodraw"
cask "muzzle"
cask "nightfall"
cask "numi"
cask "orbstack"
cask "postman"
cask "pulsar"
cask "raycast"
cask "session-manager-plugin"
cask "setapp"
cask "slack"
cask "sloth"
cask "spotify"
cask "swish"
cask "syntax-highlight"
cask "tableplus"
cask "tailscale"
cask "teamviewer"
cask "timemachineeditor"
cask "typora"
cask "viscosity"
cask "visual-studio-code"
cask "wezterm"
cask "zed"
cask "zoom"

mas "amphetamine", id: 937984704
mas "parcel",      id: 639968404
mas "rcmd",        id: 1596283165
mas "snippetslab", id: 1006087419
mas "trello",      id: 1278508951
