# zprof
zmodload zsh/zprof

# completion
zstyle ':completion:*' menu select

autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then compinit; else compinit -C; fi

source <(antibody init)

antibody bundle < ~/.zsh_plugins.txt

[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh # p10k configuration
[ -f ~/.fresh/build/shell.sh ] && source ~/.fresh/build/shell.sh # fresh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh # fzf
[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

eval "$(zoxide init zsh --cmd j --no-aliases)"

## History file configuration
HISTFILE=~/.zhistory
HISTSIZE=1000000
SAVEHIST=$HISTSIZE

## History command configuration
setopt HIST_IGNORE_ALL_DUPS # history ignore duplicates
setopt HIST_IGNORE_SPACE    # history ignore commands with leading space
setopt SHARE_HISTORY        # shared history between sessions

setopt INTERACTIVECOMMENTS  # allow interactive comments

# keyboard bindings
bindkey "^[[3~"  delete-char
bindkey "^[3;5~" delete-char

# environmental variables
# export PATH="$( gem environment gemdir )/bin:$PATH" # add path for ruby gem binaries
export PATH="/usr/local/lib/ruby/gems/2.7.0/bin:$PATH" # add path for ruby gem binaries
export PATH="/usr/local/opt/ruby/bin:$PATH" # add path for ruby
export PATH="/usr/local/sbin:$PATH" # add path for homebrew

export CLICOLOR=1                                                         # enable colours in terminal
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD                                    # colour settings for ls
export EDITOR=nano                                                        # default editor nano
export DIRENV_LOG_FORMAT=                                                 # disable direnv output

# aliases
alias k=kubectl
alias s2a="saml2aws login --skip-prompt"
alias s2c="saml2aws console"

# function precmd() { it2setkeylabel set status "Context: $( kubectl config current-context )"; }
function precmd() { it2setkeylabel set status "Context: $( awk '$1 == "current-context:" {print $2}' ~/.kube/config )"; }
